# Generated by Django 4.2.16 on 2024-12-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formation", models.CharField(max_length=200)),
                ("prioriteRetour", models.CharField(max_length=100)),
                ("typeRetour", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "attachedfiles",
                    models.FileField(blank=True, null=True, upload_to="feedback/"),
                ),
                ("consentement", models.BooleanField(default=False)),
            ],
        ),
    ]
